name: unit_test_study
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  bloc: ^8.1.2
  http: ^1.2.0
  json_rest_server: ^2.0.4
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  mocktail: ^1.0.3
